language: node_js
cache:
    directories:
        - ~/.npm
notifications:
    email: true
node_js:
    - '8'
install: npm install
jobs:
    include:
        - stage: test
          script:
              - npm run build
              - npm run lint
              - npm run test
        - stage: deploy
          if: (tag =~ ^v) AND (branch = master)
          script: npm run release
